//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GlobalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StringResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OStore.GlobalResources.StringResource", typeof(StringResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello, you can view the product by going to this link - .
        /// </summary>
        public static string Common_CopyMessage {
            get {
                return ResourceManager.GetString("Common_CopyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Delivery_Setup_btnCancel {
            get {
                return ResourceManager.GetString("Delivery_Setup_btnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Delivery_Setup_btnSave {
            get {
                return ResourceManager.GetString("Delivery_Setup_btnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipping Cost:.
        /// </summary>
        public static string Delivery_Setup_Cost {
            get {
                return ResourceManager.GetString("Delivery_Setup_Cost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Area: Bangkok, Nonthaburi, Samut Prakan, Pathum Thani.
        /// </summary>
        public static string Delivery_Setup_D1_Info {
            get {
                return ResourceManager.GetString("Delivery_Setup_D1_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name: Alpha.
        /// </summary>
        public static string Delivery_Setup_D1Name {
            get {
                return ResourceManager.GetString("Delivery_Setup_D1Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Area: Thailand.
        /// </summary>
        public static string Delivery_Setup_D2_Info {
            get {
                return ResourceManager.GetString("Delivery_Setup_D2_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name: Thaipost.
        /// </summary>
        public static string Delivery_Setup_D2Name {
            get {
                return ResourceManager.GetString("Delivery_Setup_D2Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service day: .
        /// </summary>
        public static string Delivery_Setup_ServiceDay {
            get {
                return ResourceManager.GetString("Delivery_Setup_ServiceDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Up Delivery Channel.
        /// </summary>
        public static string Delivery_Setup_Title {
            get {
                return ResourceManager.GetString("Delivery_Setup_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Exchange_Index_btnCancel {
            get {
                return ResourceManager.GetString("Exchange_Index_btnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Exchange_Index_btnSave {
            get {
                return ResourceManager.GetString("Exchange_Index_btnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string Exchange_Index_ExGrid_Contact {
            get {
                return ResourceManager.GetString("Exchange_Index_ExGrid_Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date/Time Return.
        /// </summary>
        public static string Exchange_Index_ExGrid_DateTime {
            get {
                return ResourceManager.GetString("Exchange_Index_ExGrid_DateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exchange ID.
        /// </summary>
        public static string Exchange_Index_ExGrid_ExchangeId {
            get {
                return ResourceManager.GetString("Exchange_Index_ExGrid_ExchangeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LINE.
        /// </summary>
        public static string Exchange_Index_ExGrid_LINE {
            get {
                return ResourceManager.GetString("Exchange_Index_ExGrid_LINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receiver Name.
        /// </summary>
        public static string Exchange_Index_ExGrid_Name {
            get {
                return ResourceManager.GetString("Exchange_Index_ExGrid_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order ID.
        /// </summary>
        public static string Exchange_Index_ExGrid_OrderId {
            get {
                return ResourceManager.GetString("Exchange_Index_ExGrid_OrderId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string Exchange_Index_ExGrid_Price {
            get {
                return ResourceManager.GetString("Exchange_Index_ExGrid_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Exchange_Index_ExGrid_Status {
            get {
                return ResourceManager.GetString("Exchange_Index_ExGrid_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exchanged.
        /// </summary>
        public static string Exchange_Index_ExSubTab_Exchanged {
            get {
                return ResourceManager.GetString("Exchange_Index_ExSubTab_Exchanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exchanging.
        /// </summary>
        public static string Exchange_Index_ExSubTab_Exchanging {
            get {
                return ResourceManager.GetString("Exchange_Index_ExSubTab_Exchanging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pack.
        /// </summary>
        public static string Exchange_Index_ExSubTab_Pack {
            get {
                return ResourceManager.GetString("Exchange_Index_ExSubTab_Pack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending.
        /// </summary>
        public static string Exchange_Index_ExSubTab_Pending {
            get {
                return ResourceManager.GetString("Exchange_Index_ExSubTab_Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick.
        /// </summary>
        public static string Exchange_Index_ExSubTab_Pick {
            get {
                return ResourceManager.GetString("Exchange_Index_ExSubTab_Pick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attached File.
        /// </summary>
        public static string Exchange_Index_lblAttach {
            get {
                return ResourceManager.GetString("Exchange_Index_lblAttach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select All.
        /// </summary>
        public static string Exchange_Index_lblSelectAll {
            get {
                return ResourceManager.GetString("Exchange_Index_lblSelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exchange.
        /// </summary>
        public static string Exchange_Index_MainTab_Exchange {
            get {
                return ResourceManager.GetString("Exchange_Index_MainTab_Exchange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return.
        /// </summary>
        public static string Exchange_Index_MainTab_Return {
            get {
                return ResourceManager.GetString("Exchange_Index_MainTab_Return", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return &amp; Exchange.
        /// </summary>
        public static string Exchange_Index_Title {
            get {
                return ResourceManager.GetString("Exchange_Index_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Marketing_Customer_Address {
            get {
                return ResourceManager.GetString("Marketing_Customer_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to District.
        /// </summary>
        public static string Marketing_Customer_District {
            get {
                return ResourceManager.GetString("Marketing_Customer_District", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Marketing_Customer_Email {
            get {
                return ResourceManager.GetString("Marketing_Customer_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facebook.
        /// </summary>
        public static string Marketing_Customer_Facebook {
            get {
                return ResourceManager.GetString("Marketing_Customer_Facebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Marketing_Customer_Firstname {
            get {
                return ResourceManager.GetString("Marketing_Customer_Firstname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instargram.
        /// </summary>
        public static string Marketing_Customer_Instargram {
            get {
                return ResourceManager.GetString("Marketing_Customer_Instargram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string Marketing_Customer_IsActive {
            get {
                return ResourceManager.GetString("Marketing_Customer_IsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        public static string Marketing_Customer_Lastname {
            get {
                return ResourceManager.GetString("Marketing_Customer_Lastname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line.
        /// </summary>
        public static string Marketing_Customer_Line {
            get {
                return ResourceManager.GetString("Marketing_Customer_Line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile.
        /// </summary>
        public static string Marketing_Customer_Mobile {
            get {
                return ResourceManager.GetString("Marketing_Customer_Mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nick name.
        /// </summary>
        public static string Marketing_Customer_Nickname {
            get {
                return ResourceManager.GetString("Marketing_Customer_Nickname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picture.
        /// </summary>
        public static string Marketing_Customer_Picture {
            get {
                return ResourceManager.GetString("Marketing_Customer_Picture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zip code.
        /// </summary>
        public static string Marketing_Customer_PostalCode {
            get {
                return ResourceManager.GetString("Marketing_Customer_PostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Province.
        /// </summary>
        public static string Marketing_Customer_Province {
            get {
                return ResourceManager.GetString("Marketing_Customer_Province", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subdistrict.
        /// </summary>
        public static string Marketing_Customer_SubDistrict {
            get {
                return ResourceManager.GetString("Marketing_Customer_SubDistrict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount Amount.
        /// </summary>
        public static string Marketing_Promotion_Amount {
            get {
                return ResourceManager.GetString("Marketing_Promotion_Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string Marketing_Promotion_Code {
            get {
                return ResourceManager.GetString("Marketing_Promotion_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer.
        /// </summary>
        public static string Marketing_Promotion_CustomerName {
            get {
                return ResourceManager.GetString("Marketing_Promotion_CustomerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount Type.
        /// </summary>
        public static string Marketing_Promotion_DiscountType {
            get {
                return ResourceManager.GetString("Marketing_Promotion_DiscountType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        public static string Marketing_Promotion_EffectiveDate {
            get {
                return ResourceManager.GetString("Marketing_Promotion_EffectiveDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Time.
        /// </summary>
        public static string Marketing_Promotion_EffectiveTime {
            get {
                return ResourceManager.GetString("Marketing_Promotion_EffectiveTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expire Date.
        /// </summary>
        public static string Marketing_Promotion_ExpiredDate {
            get {
                return ResourceManager.GetString("Marketing_Promotion_ExpiredDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expire Time.
        /// </summary>
        public static string Marketing_Promotion_ExpiredTime {
            get {
                return ResourceManager.GetString("Marketing_Promotion_ExpiredTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string Marketing_Promotion_IsActive {
            get {
                return ResourceManager.GetString("Marketing_Promotion_IsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How many time to use.
        /// </summary>
        public static string Marketing_Promotion_LimitPerCustomer {
            get {
                return ResourceManager.GetString("Marketing_Promotion_LimitPerCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How many time to use.
        /// </summary>
        public static string Marketing_Promotion_LimitTotal {
            get {
                return ResourceManager.GetString("Marketing_Promotion_LimitTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum Discount.
        /// </summary>
        public static string Marketing_Promotion_MaximumDiscount {
            get {
                return ResourceManager.GetString("Marketing_Promotion_MaximumDiscount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum Price.
        /// </summary>
        public static string Marketing_Promotion_MinimumPurchase {
            get {
                return ResourceManager.GetString("Marketing_Promotion_MinimumPurchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum Item.
        /// </summary>
        public static string Marketing_Promotion_MinimunItem {
            get {
                return ResourceManager.GetString("Marketing_Promotion_MinimunItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promotion name.
        /// </summary>
        public static string Marketing_Promotion_Name {
            get {
                return ResourceManager.GetString("Marketing_Promotion_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No..
        /// </summary>
        public static string Marketing_Promotion_No {
            get {
                return ResourceManager.GetString("Marketing_Promotion_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Marketing_Promotion_OrderDate {
            get {
                return ResourceManager.GetString("Marketing_Promotion_OrderDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Id.
        /// </summary>
        public static string Marketing_Promotion_OrderId {
            get {
                return ResourceManager.GetString("Marketing_Promotion_OrderId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount Percentage.
        /// </summary>
        public static string Marketing_Promotion_Percentage {
            get {
                return ResourceManager.GetString("Marketing_Promotion_Percentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Per Code.
        /// </summary>
        public static string Marketing_Promotion_PerCode {
            get {
                return ResourceManager.GetString("Marketing_Promotion_PerCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Per User.
        /// </summary>
        public static string Marketing_Promotion_PerUser {
            get {
                return ResourceManager.GetString("Marketing_Promotion_PerUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revenue.
        /// </summary>
        public static string Marketing_Promotion_Revenue {
            get {
                return ResourceManager.GetString("Marketing_Promotion_Revenue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Marketing_Promotion_Status {
            get {
                return ResourceManager.GetString("Marketing_Promotion_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New promotion code.
        /// </summary>
        public static string Marketing_Promotion_Tab_Create {
            get {
                return ResourceManager.GetString("Marketing_Promotion_Tab_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report promotion code.
        /// </summary>
        public static string Marketing_Promotion_Tab_Report {
            get {
                return ResourceManager.GetString("Marketing_Promotion_Tab_Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total used.
        /// </summary>
        public static string Marketing_Promotion_UsedQuantity {
            get {
                return ResourceManager.GetString("Marketing_Promotion_UsedQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer.
        /// </summary>
        public static string Marketing_Tab_Customer {
            get {
                return ResourceManager.GetString("Marketing_Tab_Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promotion.
        /// </summary>
        public static string Marketing_Tab_Promotion {
            get {
                return ResourceManager.GetString("Marketing_Tab_Promotion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import from.
        /// </summary>
        public static string Order_Import_Source {
            get {
                return ResourceManager.GetString("Order_Import_Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer.
        /// </summary>
        public static string Order_Manual_CustomerId {
            get {
                return ResourceManager.GetString("Order_Manual_CustomerId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deliver.
        /// </summary>
        public static string Order_Manual_DeliveryChannel {
            get {
                return ResourceManager.GetString("Order_Manual_DeliveryChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount.
        /// </summary>
        public static string Order_Manual_DiscountAmount {
            get {
                return ResourceManager.GetString("Order_Manual_DiscountAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total amount.
        /// </summary>
        public static string Order_Manual_GrandTotalAmount {
            get {
                return ResourceManager.GetString("Order_Manual_GrandTotalAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link.
        /// </summary>
        public static string Order_Manual_Link {
            get {
                return ResourceManager.GetString("Order_Manual_Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Order_Manual_OrderDate {
            get {
                return ResourceManager.GetString("Order_Manual_OrderDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Id.
        /// </summary>
        public static string Order_Manual_OrderId {
            get {
                return ResourceManager.GetString("Order_Manual_OrderId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        public static string Order_Manual_Product_Color {
            get {
                return ResourceManager.GetString("Order_Manual_Product_Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose color.
        /// </summary>
        public static string Order_Manual_Product_Color_Required {
            get {
                return ResourceManager.GetString("Order_Manual_Product_Color_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picture.
        /// </summary>
        public static string Order_Manual_Product_Image {
            get {
                return ResourceManager.GetString("Order_Manual_Product_Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Order_Manual_Product_Name {
            get {
                return ResourceManager.GetString("Order_Manual_Product_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        public static string Order_Manual_Product_OrderQuantity {
            get {
                return ResourceManager.GetString("Order_Manual_Product_OrderQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please entry quantity.
        /// </summary>
        public static string Order_Manual_Product_OrderQuantity_Required {
            get {
                return ResourceManager.GetString("Order_Manual_Product_OrderQuantity_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string Order_Manual_Product_Price {
            get {
                return ResourceManager.GetString("Order_Manual_Product_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        public static string Order_Manual_Product_Size {
            get {
                return ResourceManager.GetString("Order_Manual_Product_Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose size.
        /// </summary>
        public static string Order_Manual_Product_Size_Required {
            get {
                return ResourceManager.GetString("Order_Manual_Product_Size_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SKU.
        /// </summary>
        public static string Order_Manual_Product_SKU {
            get {
                return ResourceManager.GetString("Order_Manual_Product_SKU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock.
        /// </summary>
        public static string Order_Manual_Product_StockQuantity {
            get {
                return ResourceManager.GetString("Order_Manual_Product_StockQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product list.
        /// </summary>
        public static string Order_Manual_ProductList {
            get {
                return ResourceManager.GetString("Order_Manual_ProductList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        public static string Order_Manual_Quantity {
            get {
                return ResourceManager.GetString("Order_Manual_Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please entry quantity.
        /// </summary>
        public static string Order_Manual_Quantity_Required {
            get {
                return ResourceManager.GetString("Order_Manual_Quantity_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remark.
        /// </summary>
        public static string Order_Manual_Remark {
            get {
                return ResourceManager.GetString("Order_Manual_Remark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Order_Manual_Status {
            get {
                return ResourceManager.GetString("Order_Manual_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price product.
        /// </summary>
        public static string Order_Manual_TotalAmount {
            get {
                return ResourceManager.GetString("Order_Manual_TotalAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick &amp; Pack.
        /// </summary>
        public static string OrderManagement_PackAndPack_Title {
            get {
                return ResourceManager.GetString("OrderManagement_PackAndPack_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Ordermanagement_Pay_COD_Tab_Cancel {
            get {
                return ResourceManager.GetString("Ordermanagement_Pay_COD_Tab_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string Ordermanagement_Pay_COD_Tab_Confirm {
            get {
                return ResourceManager.GetString("Ordermanagement_Pay_COD_Tab_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uncall.
        /// </summary>
        public static string Ordermanagement_Pay_COD_Tab_Uncall {
            get {
                return ResourceManager.GetString("Ordermanagement_Pay_COD_Tab_Uncall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string OrderManagement_Pay_CustomerName {
            get {
                return ResourceManager.GetString("OrderManagement_Pay_CustomerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut off time.
        /// </summary>
        public static string OrderManagement_Pay_CutOffTime {
            get {
                return ResourceManager.GetString("OrderManagement_Pay_CutOffTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select geography.
        /// </summary>
        public static string OrderManagement_Pay_Geography {
            get {
                return ResourceManager.GetString("OrderManagement_Pay_Geography", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Code.
        /// </summary>
        public static string OrderManagement_Pay_ItemCode {
            get {
                return ResourceManager.GetString("OrderManagement_Pay_ItemCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string OrderManagement_Pay_ItemDescription {
            get {
                return ResourceManager.GetString("OrderManagement_Pay_ItemDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Line.
        /// </summary>
        public static string OrderManagement_Pay_ItemLine {
            get {
                return ResourceManager.GetString("OrderManagement_Pay_ItemLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line.
        /// </summary>
        public static string OrderManagement_Pay_Line {
            get {
                return ResourceManager.GetString("OrderManagement_Pay_Line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string OrderManagement_Pay_Mobile {
            get {
                return ResourceManager.GetString("OrderManagement_Pay_Mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date/Time.
        /// </summary>
        public static string OrderManagement_Pay_OrderDate {
            get {
                return ResourceManager.GetString("OrderManagement_Pay_OrderDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select from date.
        /// </summary>
        public static string OrderManagement_Pay_OrderDateFrom {
            get {
                return ResourceManager.GetString("OrderManagement_Pay_OrderDateFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select from to.
        /// </summary>
        public static string OrderManagement_Pay_OrderDateTo {
            get {
                return ResourceManager.GetString("OrderManagement_Pay_OrderDateTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Id.
        /// </summary>
        public static string OrderManagement_Pay_OrderId {
            get {
                return ResourceManager.GetString("OrderManagement_Pay_OrderId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick up time.
        /// </summary>
        public static string OrderManagement_Pay_PickUpTime {
            get {
                return ResourceManager.GetString("OrderManagement_Pay_PickUpTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paid confirm.
        /// </summary>
        public static string Ordermanagement_Pay_Prepay_Tab_PaidConfirm {
            get {
                return ResourceManager.GetString("Ordermanagement_Pay_Prepay_Tab_PaidConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post.
        /// </summary>
        public static string Ordermanagement_Pay_Prepay_Tab_Post {
            get {
                return ResourceManager.GetString("Ordermanagement_Pay_Prepay_Tab_Post", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unpost.
        /// </summary>
        public static string Ordermanagement_Pay_Prepay_Tab_Unpost {
            get {
                return ResourceManager.GetString("Ordermanagement_Pay_Prepay_Tab_Unpost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string OrderManagement_Pay_Price {
            get {
                return ResourceManager.GetString("OrderManagement_Pay_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason.
        /// </summary>
        public static string OrderManagement_Pay_Reason {
            get {
                return ResourceManager.GetString("OrderManagement_Pay_Reason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remark.
        /// </summary>
        public static string OrderManagement_Pay_Remark {
            get {
                return ResourceManager.GetString("OrderManagement_Pay_Remark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select sale channel.
        /// </summary>
        public static string OrderManagement_Pay_SaleChannelId {
            get {
                return ResourceManager.GetString("OrderManagement_Pay_SaleChannelId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string OrderManagement_Pay_StatusId {
            get {
                return ResourceManager.GetString("OrderManagement_Pay_StatusId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store Staff.
        /// </summary>
        public static string OrderManagement_Pay_StoreStaff {
            get {
                return ResourceManager.GetString("OrderManagement_Pay_StoreStaff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COD.
        /// </summary>
        public static string Ordermanagement_Pay_Tab_COD {
            get {
                return ResourceManager.GetString("Ordermanagement_Pay_Tab_COD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prepay.
        /// </summary>
        public static string Ordermanagement_Pay_Tab_Prepay {
            get {
                return ResourceManager.GetString("Ordermanagement_Pay_Tab_Prepay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Laps.
        /// </summary>
        public static string OrderManagement_Pay_TimeLap {
            get {
                return ResourceManager.GetString("OrderManagement_Pay_TimeLap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay.
        /// </summary>
        public static string OrderManagement_Pay_Title {
            get {
                return ResourceManager.GetString("OrderManagement_Pay_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pack.
        /// </summary>
        public static string Ordermanagement_PickPack_Tab_Pack {
            get {
                return ResourceManager.GetString("Ordermanagement_PickPack_Tab_Pack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick.
        /// </summary>
        public static string Ordermanagement_PickPack_Tab_Pick {
            get {
                return ResourceManager.GetString("Ordermanagement_PickPack_Tab_Pick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deliver.
        /// </summary>
        public static string OrderManagement_Ship_Deliver {
            get {
                return ResourceManager.GetString("OrderManagement_Ship_Deliver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select all.
        /// </summary>
        public static string OrderManagement_Ship_SelectAll {
            get {
                return ResourceManager.GetString("OrderManagement_Ship_SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ship.
        /// </summary>
        public static string OrderManagement_Ship_Title {
            get {
                return ResourceManager.GetString("OrderManagement_Ship_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay.
        /// </summary>
        public static string Ordermanagement_Tab_Title_Pay {
            get {
                return ResourceManager.GetString("Ordermanagement_Tab_Title_Pay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick &amp; pack.
        /// </summary>
        public static string Ordermanagement_Tab_Title_PickPack {
            get {
                return ResourceManager.GetString("Ordermanagement_Tab_Title_PickPack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ship.
        /// </summary>
        public static string Ordermanagement_Tab_Title_Ship {
            get {
                return ResourceManager.GetString("Ordermanagement_Tab_Title_Ship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Management.
        /// </summary>
        public static string OrderManagement_Title {
            get {
                return ResourceManager.GetString("OrderManagement_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string Product_Create_Category {
            get {
                return ResourceManager.GetString("Product_Create_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colour.
        /// </summary>
        public static string Product_Create_Color {
            get {
                return ResourceManager.GetString("Product_Create_Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost price.
        /// </summary>
        public static string Product_Create_Cost {
            get {
                return ResourceManager.GetString("Product_Create_Cost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days.
        /// </summary>
        public static string Product_Create_Days {
            get {
                return ResourceManager.GetString("Product_Create_Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Product_Create_Description {
            get {
                return ResourceManager.GetString("Product_Create_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string Product_Create_IsActive {
            get {
                return ResourceManager.GetString("Product_Create_IsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colour.
        /// </summary>
        public static string Product_Create_Item_Color {
            get {
                return ResourceManager.GetString("Product_Create_Item_Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost.
        /// </summary>
        public static string Product_Create_Item_Cost {
            get {
                return ResourceManager.GetString("Product_Create_Item_Cost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material.
        /// </summary>
        public static string Product_Create_Item_Material {
            get {
                return ResourceManager.GetString("Product_Create_Item_Material", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manufacturer SKU.
        /// </summary>
        public static string Product_Create_Item_MFSKU {
            get {
                return ResourceManager.GetString("Product_Create_Item_MFSKU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string Product_Create_Item_Price {
            get {
                return ResourceManager.GetString("Product_Create_Item_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        public static string Product_Create_Item_Quantity {
            get {
                return ResourceManager.GetString("Product_Create_Item_Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        public static string Product_Create_Item_Size {
            get {
                return ResourceManager.GetString("Product_Create_Item_Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SKU.
        /// </summary>
        public static string Product_Create_Item_SKU {
            get {
                return ResourceManager.GetString("Product_Create_Item_SKU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sell Price.
        /// </summary>
        public static string Product_Create_Item_SpecialPrice {
            get {
                return ResourceManager.GetString("Product_Create_Item_SpecialPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Universal SKU.
        /// </summary>
        public static string Product_Create_Item_UNSKU {
            get {
                return ResourceManager.GetString("Product_Create_Item_UNSKU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material.
        /// </summary>
        public static string Product_Create_Material {
            get {
                return ResourceManager.GetString("Product_Create_Material", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Product_Create_Name {
            get {
                return ResourceManager.GetString("Product_Create_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pre-Order.
        /// </summary>
        public static string Product_Create_PrepareDate {
            get {
                return ResourceManager.GetString("Product_Create_PrepareDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string Product_Create_Price {
            get {
                return ResourceManager.GetString("Product_Create_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show when out of stock.
        /// </summary>
        public static string Product_Create_ShowWhenOutStock {
            get {
                return ResourceManager.GetString("Product_Create_ShowWhenOutStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        public static string Product_Create_Size {
            get {
                return ResourceManager.GetString("Product_Create_Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sell price.
        /// </summary>
        public static string Product_Create_SpecialPrice {
            get {
                return ResourceManager.GetString("Product_Create_SpecialPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags.
        /// </summary>
        public static string Product_Create_Tag {
            get {
                return ResourceManager.GetString("Product_Create_Tag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create product.
        /// </summary>
        public static string Product_Create_Title {
            get {
                return ResourceManager.GetString("Product_Create_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Pictures.
        /// </summary>
        public static string Product_Create_UploadImage {
            get {
                return ResourceManager.GetString("Product_Create_UploadImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Us:.
        /// </summary>
        public static string Shop_Edit_AboutUs {
            get {
                return ResourceManager.GetString("Shop_Edit_AboutUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Shop_Edit_btnCancel {
            get {
                return ResourceManager.GetString("Shop_Edit_btnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Shop_Edit_btnSave {
            get {
                return ResourceManager.GetString("Shop_Edit_btnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address:.
        /// </summary>
        public static string Shop_Edit_ShopAddress {
            get {
                return ResourceManager.GetString("Shop_Edit_ShopAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to District:.
        /// </summary>
        public static string Shop_Edit_ShopDistrict {
            get {
                return ResourceManager.GetString("Shop_Edit_ShopDistrict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facebook:.
        /// </summary>
        public static string Shop_Edit_ShopFB {
            get {
                return ResourceManager.GetString("Shop_Edit_ShopFB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instagram:.
        /// </summary>
        public static string Shop_Edit_ShopIG {
            get {
                return ResourceManager.GetString("Shop_Edit_ShopIG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LINE:.
        /// </summary>
        public static string Shop_Edit_ShopLine {
            get {
                return ResourceManager.GetString("Shop_Edit_ShopLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logo:.
        /// </summary>
        public static string Shop_Edit_ShopLogo {
            get {
                return ResourceManager.GetString("Shop_Edit_ShopLogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shop Names:.
        /// </summary>
        public static string Shop_Edit_ShopName {
            get {
                return ResourceManager.GetString("Shop_Edit_ShopName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Province:.
        /// </summary>
        public static string Shop_Edit_ShopProvince {
            get {
                return ResourceManager.GetString("Shop_Edit_ShopProvince", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub-District:.
        /// </summary>
        public static string Shop_Edit_ShopSubDistrict {
            get {
                return ResourceManager.GetString("Shop_Edit_ShopSubDistrict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tel:.
        /// </summary>
        public static string Shop_Edit_ShopTelephone {
            get {
                return ResourceManager.GetString("Shop_Edit_ShopTelephone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zip Code:.
        /// </summary>
        public static string Shop_Edit_ShopZipCode {
            get {
                return ResourceManager.GetString("Shop_Edit_ShopZipCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Us.
        /// </summary>
        public static string Shop_Edit_TabAbout {
            get {
                return ResourceManager.GetString("Shop_Edit_TabAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shop Detail.
        /// </summary>
        public static string Shop_Edit_TabDetail {
            get {
                return ResourceManager.GetString("Shop_Edit_TabDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FAQs.
        /// </summary>
        public static string Shop_Edit_TabFAQs {
            get {
                return ResourceManager.GetString("Shop_Edit_TabFAQs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shop Info.
        /// </summary>
        public static string Shop_Edit_Title {
            get {
                return ResourceManager.GetString("Shop_Edit_Title", resourceCulture);
            }
        }
    }
}
