//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OStore.Data.EF
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class PersonOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PersonOrder()
        {
            this.PersonOrderDetails = new HashSet<PersonOrderDetail>();
        }
    
        public int Id { get; set; }
        public int ShopId { get; set; }
        public int PersonId { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<int> PromotionId { get; set; }
        public Nullable<decimal> NetPrice { get; set; }
        public Nullable<int> ShippingAddressId { get; set; }
        public Nullable<int> BillingAddressId { get; set; }
        public Nullable<int> SaleChannelId { get; set; }
        public Nullable<int> OrderStatusId { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<int> UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    
        public virtual Person Person { get; set; }
        public virtual PersonAddress PersonAddress { get; set; }
        public virtual PersonAddress PersonAddress1 { get; set; }
        public virtual Promotion Promotion { get; set; }
        public virtual SaleChannel SaleChannel { get; set; }
        public virtual Shop Shop { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonOrderDetail> PersonOrderDetails { get; set; }
    }
}
