//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OStore.Data.EF
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class ProductMapVariantDetail
    {
        public int ProductId { get; set; }
        public int ProductVariantId { get; set; }
        public int ProductVariantDetailId { get; set; }
        public string Value1 { get; set; }
        public string Value2 { get; set; }
        public bool Show { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<int> UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    
        public virtual ProductMapVariant ProductMapVariant { get; set; }
        public virtual ProductVariantDetail ProductVariantDetail { get; set; }
    }
}
