//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OStore.Data.EF
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class ShopPaymentAccount
    {
        public int Id { get; set; }
        public int ShopMapPaymentChannelId { get; set; }
        public string Account { get; set; }
        public Nullable<int> BankId { get; set; }
        public string Branch { get; set; }
        public string Name { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<int> UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    
        public virtual Bank Bank { get; set; }
        public virtual ShopMapPaymentChannel ShopMapPaymentChannel { get; set; }
    }
}
