//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.StringResource", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Delivery_Setup_btnCancel {
            get {
                return ResourceManager.GetString("Delivery_Setup_btnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Delivery_Setup_btnSave {
            get {
                return ResourceManager.GetString("Delivery_Setup_btnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipping Cost:.
        /// </summary>
        internal static string Delivery_Setup_Cost {
            get {
                return ResourceManager.GetString("Delivery_Setup_Cost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name: Alpha.
        /// </summary>
        internal static string Delivery_Setup_D1Name {
            get {
                return ResourceManager.GetString("Delivery_Setup_D1Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Area: Bangkok, Nonthaburi, Samut Prakan, Pathum Thani.
        /// </summary>
        internal static string Delivery_Setup_D1_Info {
            get {
                return ResourceManager.GetString("Delivery_Setup_D1_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name: Thaipost.
        /// </summary>
        internal static string Delivery_Setup_D2Name {
            get {
                return ResourceManager.GetString("Delivery_Setup_D2Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Area: Thailand.
        /// </summary>
        internal static string Delivery_Setup_D2_Info {
            get {
                return ResourceManager.GetString("Delivery_Setup_D2_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service day: .
        /// </summary>
        internal static string Delivery_Setup_ServiceDay {
            get {
                return ResourceManager.GetString("Delivery_Setup_ServiceDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Up Delivery Channel.
        /// </summary>
        internal static string Delivery_Setup_Title {
            get {
                return ResourceManager.GetString("Delivery_Setup_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer.
        /// </summary>
        internal static string Order_Manual_CustomerId {
            get {
                return ResourceManager.GetString("Order_Manual_CustomerId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deliver.
        /// </summary>
        internal static string Order_Manual_DeliveryChannel {
            get {
                return ResourceManager.GetString("Order_Manual_DeliveryChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount.
        /// </summary>
        internal static string Order_Manual_DiscountAmount {
            get {
                return ResourceManager.GetString("Order_Manual_DiscountAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total amount.
        /// </summary>
        internal static string Order_Manual_GrandTotalAmount {
            get {
                return ResourceManager.GetString("Order_Manual_GrandTotalAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link.
        /// </summary>
        internal static string Order_Manual_Link {
            get {
                return ResourceManager.GetString("Order_Manual_Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string Order_Manual_OrderDate {
            get {
                return ResourceManager.GetString("Order_Manual_OrderDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Id.
        /// </summary>
        internal static string Order_Manual_OrderId {
            get {
                return ResourceManager.GetString("Order_Manual_OrderId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product list.
        /// </summary>
        internal static string Order_Manual_ProductList {
            get {
                return ResourceManager.GetString("Order_Manual_ProductList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        internal static string Order_Manual_Product_Color {
            get {
                return ResourceManager.GetString("Order_Manual_Product_Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose color.
        /// </summary>
        internal static string Order_Manual_Product_Color_Required {
            get {
                return ResourceManager.GetString("Order_Manual_Product_Color_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picture.
        /// </summary>
        internal static string Order_Manual_Product_Image {
            get {
                return ResourceManager.GetString("Order_Manual_Product_Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Order_Manual_Product_Name {
            get {
                return ResourceManager.GetString("Order_Manual_Product_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        internal static string Order_Manual_Product_OrderQuantity {
            get {
                return ResourceManager.GetString("Order_Manual_Product_OrderQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please entry quantity.
        /// </summary>
        internal static string Order_Manual_Product_OrderQuantity_Required {
            get {
                return ResourceManager.GetString("Order_Manual_Product_OrderQuantity_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        internal static string Order_Manual_Product_Price {
            get {
                return ResourceManager.GetString("Order_Manual_Product_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        internal static string Order_Manual_Product_Size {
            get {
                return ResourceManager.GetString("Order_Manual_Product_Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose size.
        /// </summary>
        internal static string Order_Manual_Product_Size_Required {
            get {
                return ResourceManager.GetString("Order_Manual_Product_Size_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SKU.
        /// </summary>
        internal static string Order_Manual_Product_SKU {
            get {
                return ResourceManager.GetString("Order_Manual_Product_SKU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock.
        /// </summary>
        internal static string Order_Manual_Product_StockQuantity {
            get {
                return ResourceManager.GetString("Order_Manual_Product_StockQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        internal static string Order_Manual_Quantity {
            get {
                return ResourceManager.GetString("Order_Manual_Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please entry quantity.
        /// </summary>
        internal static string Order_Manual_Quantity_Required {
            get {
                return ResourceManager.GetString("Order_Manual_Quantity_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remark.
        /// </summary>
        internal static string Order_Manual_Remark {
            get {
                return ResourceManager.GetString("Order_Manual_Remark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string Order_Manual_Status {
            get {
                return ResourceManager.GetString("Order_Manual_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price product.
        /// </summary>
        internal static string Order_Manual_TotalAmount {
            get {
                return ResourceManager.GetString("Order_Manual_TotalAmount", resourceCulture);
            }
        }
    }
}
